### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by newpest** [iprada/Circle-Map#103]

**Comment by iprada** [comment]
Hi,

You will have to elaborate a bit if you want help. I should not be guessing

best,

Iñigo

**Comment by newpest** [comment]
I get the  error when I run Circle-Map ReadExtractor：
```
Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/multiprocessing/managers.py", line 608, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/local/lib/python3.8/multiprocessing/managers.py", line 154, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/usr/local/bin/Circle-Map", line 6, in <module>
    from circlemap.circle_map import main
  File "/usr/local/lib/python3.8/site-packages/circlemap/circle_map.py", line 33, in <module>
    from circlemap.bam2bam import bam2bam
  File "/usr/local/lib/python3.8/site-packages/circlemap/bam2bam.py", line 39, in <module>
    class bam2bam:
  File "/usr/local/lib/python3.8/site-packages/circlemap/bam2bam.py", line 42, in bam2bam
    queue = mp.Manager().Queue()
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by iprada** [comment]
Hi,

The error corresponds to bam2bam. Not ReadExtractor.  I am very happy to help the community to the extend I can but you have to put an effort if you want my help. I am a human and I do not have superpowers. I need background, a description of the problem you encounter and a minimal description of what you are trying to do. The more elaborate, the merrier. 

best,

Iñigo

**Comment by newpest** [comment]
Circle-Map:v1.1.4 -bam2bam.py uses multiprocessing.Manger().Queue() for process communication, but it results in an error: [AF_UNIX path too long](https://github.com/iprada/Circle-Map/issues/103#top)

**Comment by iprada** [comment]
Based on the error your file paths are too long. Also, bam2bam never left the experimental phase
