### ISSUE TITLE
Latest biopython version breaks Alphabet dependency

### ISSUE THREAD

**Issue by johnstonmj** [iprada/Circle-Map#47]
I encountered the error:
`ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information`

This seems to have changed with [biopython 1.78](https://biopython.org/wiki/Alphabet)
Installing biopython=1.77 fixed this issue for me.

Perhaps update the conda recipe to specify biopython=1.77?

**Comment by iprada** [comment]
Hi John!

Thanks for reporting! and thanks for solving it. I am very busy right now, and you have made my life easier. This are the best type of issues I can get.  I will update the bioconda recipe tomorrow. 

Best,

Iñigo

**Comment by kpkhushi15** [comment]
Hi John!

Error encountered:
Traceback (most recent call last):
  File "/home/group_srivatsan02/PROGRAMS/SYSTEM/anaconda3/bin/Circle-Map", line 5, in <module>
    from circlemap.circle_map import main
  File "/home/group_srivatsan02/PROGRAMS/SYSTEM/anaconda3/lib/python3.8/site-packages/circlemap/circle_map.py", line 39, in <module>
    from circlemap.simulations import sim_ecc_reads
  File "/home/group_srivatsan02/PROGRAMS/SYSTEM/anaconda3/lib/python3.8/site-packages/circlemap/simulations.py", line 30, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/group_srivatsan02/PROGRAMS/SYSTEM/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.


I encountered the same issue.
After seeing your post I chnaged the bipython version==1.77 and now error got fixed.

Thankx to post this issue.

**Comment by kpkhushi15** [comment]
> I encountered the error:
> `` ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information ``
> 
> This seems to have changed with [biopython 1.78](https://biopython.org/wiki/Alphabet)
> Installing biopython=1.77 fixed this issue for me.
> 
> Perhaps update the conda recipe to specify biopython=1.77?

Hi John!
I encountered the same issue.
After seeing your post I changed the biopython version==1.77 and now error got fixed. I am able to run the commands successfully.

Thankx for posting this issue.

**Comment by mglgc** [comment]
> Hi John!
> 
> Thanks for reporting! and thanks for solving it. I am very busy right now, and you have made my life easier. This are the best type of issues I can get. I will update the bioconda recipe tomorrow.
> 
> Best,
> 
> Iñigo

Hi,
Actually, the code is not fixed to date. I had to remove the importing Bio.Alphabet module line from simulations.py script in order to fix the issue.
Cheers.

**Comment by iprada** [comment]
Hi, 

Based on the commit https://github.com/iprada/Circle-Map/commit/20d52b5533d67e8aab397f418d6e06e9a0d13b0f this was handled as it ensures that biopython 1.77 is used. Which version of biopython are you using?

best,

Iñigo

**Comment by mglgc** [comment]
> Hi,
> 
> Based on the commit [20d52b5](https://github.com/iprada/Circle-Map/commit/20d52b5533d67e8aab397f418d6e06e9a0d13b0f) this was handled as it ensures that biopython 1.77 is used. Which version of biopython are you using?
> 
> best,
> 
> Iñigo

Hi Iñigo,
The biopython 1.84 version.

Cheers.

**Comment by iprada** [comment]
Ho wo do install circle-map? using biopython 1.77 should fix things.

best,

Iñigo

**Comment by mglgc** [comment]
> Ho wo do install circle-map? using biopython 1.77 should fix things.
> 
> best,
> 
> Iñigo

Using conda as described in the Code Installation section: conda install -c bioconda circle-map

Best.

**Comment by iprada** [comment]
I think the the setup.py should take care of installing biopython 1.77 but I might be wrong. Downgrading to 1.77 should do the job for you

**Comment by G-Thomson** [comment]
For some reason it looks like the version number on bioconda was not updated when the version of biopython was set to 1.77 (https://anaconda.org/bioconda/circle-map/files). So when you don't specify the build the older version gets installed. 

Try `conda install -c bioconda circle-map=1.1.4=pyh5e36f6f_2`
